src/Controller/Backend/AdminController.php
<?php

namespace App\Controller\Backend;

use App\Repository\ConfigRepository;
use App\Repository\UserRepository;
use App\Repository\VisitorRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class AdminController
 * @package App\Controller
 * @Route("/admin")
 */
class AdminController extends BaseController {

    /**
     * @Route("/", name="admin_start")
     */
    public function start()
    {
        return $this->redirectToRoute("admin_dashboard");
    }

    /**
     * @Route("/dashboard", name="admin_dashboard")
     *
     * @param UserRepository $userRepository
     * @param BusinessRepository $businessRepository
     * @param ServiceRepository $serviceRepository
     * @param ConfigRepository $configRepository
     * @param VisitorRepository $visitorRepository
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function index(UserRepository $userRepository, ConfigRepository $configRepository,
            VisitorRepository $visitorRepository )
    {

        if (in_array('ROLE_CLIENT', $this->getUser()->getRoles())) {
            return $this->redirectToRoute('logout');
        }

        list($labels, $values) = $visitorRepository->findVisitInLabelAndValue();

        return $this->render('backend/admin/dashboard.html.twig', [
                    'users' => $userRepository->count(['enabled' => true]),
            'visitors' => empty($config = $configRepository->findOneBy(['name' => 'visitors'])) ? 0 : $config->getContent(),
                    'labels' => json_encode($labels, 1),
            'values' => json_encode($values, 1),
        ]);
    }

}

src/Controller/Backend/BaseController.php
<?php

namespace App\Controller\Backend;

use App\Entity\User;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\Exception\FileNotFoundException;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpKernel\KernelInterface;

abstract class BaseController extends AbstractController
{
    private $em;
    protected $dir_to_save = '/public/assets/images';
    private $kernel;

    public function __construct(EntityManagerInterface $em, KernelInterface $kernel)
    {
        $this->em = $em;
        $this->kernel = $kernel;
    }

    /**
     * @return User|null
     */
    protected function getUser(): ?User
    {
        return parent::getUser();
    }

    /**
     * @return EntityManagerInterface
     */
    public function getEM(): EntityManagerInterface
    {
        return $this->em;
    }

    /**
     * @param EntityManagerInterface $em
     */
    public function setEM(EntityManagerInterface $em)
    {
        $this->em = $em;
    }

    /**
     * @return KernelInterface
     */
    public function getKernel(): KernelInterface
    {
        return $this->kernel;
    }

    /**
     * @param KernelInterface $kernel
     */
    public function setKernel(KernelInterface $kernel)
    {
        $this->kernel = $kernel;
    }


    /**
     * This function check if exist the path, if not exist create it and move the file to the destination defined
     *
     * @param $file
     * @param null $file_name
     * @param bool $set_time_in_name
     * @return bool|null|string
     */
    public function upload($file, $file_name = null, $set_time_in_name = false)
    {
        // Check if exist directory, if not exist create it
        if (!is_dir($this->kernel->getProjectDir() . $this->dir_to_save)) {
            $directory = $this->kernel->getProjectDir();

            $name_dirs_to_create = explode('/', $this->dir_to_save);
            foreach ($name_dirs_to_create as $dir)
            {
                $directory .= $dir;
                if (!is_dir($directory))
                {
                    mkdir($directory);
                }
                $directory .= '/';
            }
        }

        // If not exit file to upload and the file name has assigned value
        if
        (
            empty($file)
            &&
            !empty($file_name)
        )
        {
            try
            {
                if (is_file($this->kernel->getProjectDir(). $this->dir_to_save. $file_name))
                {
                    $file = new UploadedFile($this->kernel->getProjectDir() . $this->dir_to_save, $file_name);
                }
                else
                {
                    throw new FileNotFoundException();
                }
            }
            catch (FileNotFoundException $e)
            {
                error_log( $e->getMessage() );
            }
            catch (FileException $e)
            {
                error_log( $e->getMessage() );
            }

        }

        //Not empty file to upload
        if ( !empty( $file ) )
        {
            //Get the name of file
            $name = $set_time_in_name ? time() . "_" . $file->getClientOriginalName() : $file->getClientOriginalName();
            // Construct the route to save the file
            $dir = $this->kernel->getProjectDir() . $this->dir_to_save;
            //Move the file to the constructed route
            $file->move($dir, $name);

            return $name;
        }

        return false;
    }

    /**
     * This function converts an array in a string separates by the parameter received
     *
     * @param array $array_in
     * @param string $separator
     * @return bool|string
     */
    public function array_to_string(Array $array_in, string $separator = '|')
    {
        $string_result = '';

        for ( $i = 0; $i < count($array_in); $i ++ )
        {
            $string_result .= $array_in[$i] . $separator;
        }

        return !empty($string_result) ? substr( $string_result, 0, strlen($string_result) - 1 ) : '';
    }


    /**
     * Removes image from a path
     *
     * @param string $path
     * @param string $image
     */
    public function remove_image(string $path = "/public/assets/images/", string $image)
    {
        $file_name = $this->kernel->getProjectDir() . $path . $image;
        if (is_file($file_name))
        {
            unlink($file_name);
        }
    }

    /**
     * Returns TRUE if is a client, otherwise returns FALSE
     *
     * @return bool
     */
    public function is_client()
    {

        return in_array('ROLE_CLIENT', $this->getUser()->getRoles());
    }

    /**
     * Returns TRUE if is administrator, otherwise returns FALSE
     *
     * @return bool
     */
    public function is_admin()
    {

        return in_array('ROLE_ADMIN', $this->getUser()->getRoles());
    }

    /**
     * Returns TRUE if is inactive client, otherwise returns FALSE
     *
     * @return bool
     */
    public function is_inactive_client()
    {

        return in_array('ROLE_CLIENT', $this->getUser()->getRoles()) && !$this->getUser()->getReady();
    }

}

src/Controller/Backend/ClientController.php
<?php

namespace App\Controller\Backend;

use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use App\Entity\Plan;
use App\Repository\PlanRepository;
use App\Entity\Contract;
use App\Repository\ContractRepository;
use App\Repository\TransactionRepository;
use App\Repository\AccountRepository;
use App\Classes\StringUtil;

/**
 * Class DashboardController
 * @package App\Controller
 * @Route("/members")
 */
class ClientController extends BaseController {

    /**
     * @Route("/", name="client_start")
     */
    public function start() {
        return $this->redirectToRoute("client_dashboard");
    }

    /**
     * @Route("/dashboard", name="client_dashboard")
     */
    public function index(TransactionRepository $transactionRepository) {

        if (!$this->is_client()) {
            return $this->redirectToRoute('logout');
        }

        return $this->render('backend/client/dashboard.html.twig', [
                    'active' => 'members',
                    'subactive' => 'dashboard',
                    'backend' => true,
                    'account' => $this->getUser()->getAccount(),
                    'lastTransactions' => $transactionRepository->findLastRecord(5)
        ]);
    }

    /**
     * @Route("/contract", name="client_contract")
     */
    public function newContract(PlanRepository $planRepository) {
        if (!$this->is_client()) {
            return $this->redirectToRoute('logout');
        }

        $plans = $planRepository->findAllOrdered();

        return $this->render('backend/client/contract.html.twig', [
                    'active' => 'members',
                    'subactive' => 'contract',
                    'backend' => true,
                    'plans' => $plans,
                    'colors' => Plan::COLORS
        ]);
    }

    /**
     * @Route("/contract/payment", name="client_contract_payment")
     */
    public function newContractPayment(Request $request, PlanRepository $planRepository) {
        if (!$this->is_client()) {
            return $this->redirectToRoute('logout');
        }

        $planVar = $request->request->get('drop');

        $planId = substr($planVar, 2);

        return $this->render('backend/client/contract_payment.html.twig', [
                    'active' => 'members',
                    'subactive' => 'contract',
                    'backend' => true,
                    'plan' => $planRepository->find($planId),
                    'colors' => Plan::COLORS,
                    'account' => $this->getUser()->getAccount()
        ]);
    }

    /**
     * @Route("/contract/payment/balance", name="client_contract_payment_balance")
     */
    public function newContractPaymentBalance(Request $request, PlanRepository $planRepository,
            ContractRepository $contractRepository, TransactionRepository $transactionRepository,
            AccountRepository $accountRepository) {
        if (!$this->is_client()) {
            return $this->redirectToRoute('logout');
        }

        $planVar = $request->request->get('drop');

        $planId = substr($planVar, 2);

        $plan = $planRepository->find($planId);

        $code = $contractRepository->generateNextCode();

        $account = $this->getUser()->getAccount();

        $contract = new Contract($code, $account, $plan, 'balance', 'USD');

        $this->getEM()->persist($contract);
        $this->getEM()->flush();

        $transactionRepository->create($account, 0, $plan->getValue(), 'Contrato ' . $contract->getCode() . ' (' . $plan->getCompleteName() . ') con saldo interno');

        $accountRepository->update($account, 0, $plan->getValue());

        $this->addFlash('success', 'Plan ' . $plan->getName() . ' ' . StringUtil::numberToRoman($plan->getLevel()) . ' adquirido con éxito');

        return $this->redirectToRoute('client_dashboard');
    }

    /**
     * @Route("/account/update", name="client_account_update")
     */
    public function accountUpdate() {
        if (!$this->is_client()) {
            return $this->redirectToRoute('logout');
        }

        $account = $this->getUser()->getAccount();
        
        $this->getEM()->getRepository('App:Account')->update($account);

        return new Response('Ok');
    }

}

src/Controller/Backend/ConfigController.php
<?php

namespace App\Controller\Backend;

use App\Entity\Config;
use App\Form\ConfigType;
use App\Repository\ConfigRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
 * @Route("/admin/configuracion")
 * @IsGranted("ROLE_ADMIN")
 */
class ConfigController extends BaseController
{
    /**
     * @Route("/", name="config_index", methods={"GET"})
     *
     * @param ConfigRepository $configRepository
     * @return Response
     */
    public function index(ConfigRepository $configRepository): Response
    {
        return $this->render('backend/config/index.html.twig', [
            'configs' => $configRepository->findAll(),
            'page_active' => 'config',
        ]);
    }

    /**
     * @Route("/nueva", name="config_new", methods={"GET","POST"})
     *
     * @param Request $request
     * @return Response
     */
    public function new(Request $request): Response
    {
        $config = new Config();
        $form = $this->createForm(ConfigType::class, $config);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid())
        {
            $this->getEM()->persist($config);
            $this->getEM()->flush();
            $this->addFlash('success', 'La variable de configuración ' . $config->getName() . ' fue creada exitosamente');

            return $this->redirectToRoute('config_index');
        }

        return $this->render('backend/config/new.html.twig', [
            'config' => $config,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}/editar", name="config_edit", methods={"GET","POST"})
     *
     * @param Request $request
     * @param Config $config
     * @return Response
     */
    public function edit(Request $request, Config $config): Response
    {
        $form = $this->createForm(ConfigType::class, $config);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid())
        {
            $this->getEM()->flush();
            $this->addFlash('success', 'La variable de configuración ' . $config->getName() . ' fue actualizada exitosamente');

            return $this->redirectToRoute('config_index');
        }

        return $this->render('backend/config/edit.html.twig', [
            'config' => $config,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="config_delete", methods={"GET"})
     *
     * @param Request $request
     * @param Config $config
     * @return Response
     */
    public function delete(Request $request, Config $config): Response
    {
        $this->getEM()->remove($config);
        $this->getEM()->flush();
        $this->addFlash('success', 'La variable de configuración ' . $config->getName() . ' fue eliminada exitosamente');

        return $this->redirectToRoute('config_index');
    }
}

templates/backend/client/contract.html.twig
{% extends "base.html.twig" %}

{% block title %}- Nuevo Contrato{% endblock %}

{% block content %}
    <div class="container-fluid">
        <!-- Small boxes (Stat box) -->
        <div class="row">

            <div id="menu" class="col-sm-3 acc-menu">
                {% include 'backend/client/left-menu.html.twig' %}
            </div>

            <div class="col-sm-9 acc-stat">

                {% set last_plan='' %}
                {% for plan in plans %}
                    {% if last_plan!=plan.name %}
                        {% set last_plan=plan.name %}
                        <p class="col-xs-12 plan-name">{{ plan.name }}</p>
                    {% endif %}
                    <div class="col-lg-3 acc-stat-block">
                        <div class="col-xs-12">
                            <div class="acc-stat-top {{ colors['background'][plan.priority] }}">
                                <p class="plan-level text-center">{{ plan.level|roman }}</p>
                                <p class="plan-value text-center">{{ plan.value|number_format(0,'','') }} USD</p>
                            </div>
                                <div class="acc-stat-bottom {{ colors['border'][plan.priority] }}" data-drop="{{ plan.priority~plan.level~plan.id }}">
                                    <a href="#" class="deposit">Contratar</a>
                                </div>
                        </div>
                    </div>
                {% endfor %}

            </div>
        </div>
        <!-- /.row -->
    </div><!-- /.container-fluid -->
{% endblock %}

{% block javascripts %}
    <form id="drop-form" method="post" action="{{ path('client_contract_payment') }}"><input id="drop" name="drop" type="text" value="" /></form>
    <script>
        function myFunction() {
            var copyText = document.getElementById("myInput");
            copyText.select();
            document.execCommand("copy");
        }
        window.onload = function () {
            document.querySelector('.link.success').addEventListener('click', () => console.log('Copy done.'));
        };
        $(document).ready(function () {
            $('.acc-stat-bottom').click(function () {
                $("#drop").val($(this).attr('data-drop'));
                $("#drop-form").submit();
            });
        });
    </script>
{% endblock %}

templates/backend/client/contract_payment.html.twig
{% extends "base.html.twig" %}

{% block title %}- Nuevo Contrato{% endblock %}

{% block content %}
    <div class="container-fluid">
        <!-- Small boxes (Stat box) -->
        <div class="row">

            <div id="menu" class="col-sm-3 acc-menu">
                {% include 'backend/client/left-menu.html.twig' %}
            </div>

            <div class="col-sm-9 acc-stat">

                <p class="col-xs-12 plan-name">{{ plan.name }} {{ plan.level|roman }} - {{ plan.value|number_format(0,'','') }} USD</p>

                <div class="col-xs-12 referral-link m-t-50">
                    <div class="col-lg-3 referral-link-left payment">
                        Su saldo
                    </div>
                    <div class="col-lg-9 referral-link-right">
                        <div class="col-lg-9">
                            <span class="payment-account-balance text-center">{{ app.user.account.balance }} USD</span>
                        </div>
                            <div class="col-lg-3 text-center">
                                {% if plan.value <= app.user.account.balance %}
                                    <a class="btn btn-large deposit" id="balance-contract" href="#">Contratar</a>
                                {% endif %}
                            </div>
                    </div>
                </div>

                <div class="col-xs-12">

                    <p class="acc-p m-t-50">
                        <img src="{{ asset('assets/images/deposit.svg') }}" alt=""> Depositar
                    </p>
                    <div class="wallets m-t-25">
                        <label for="process_18">
                            <input type="radio" name="type" id="process_18" class="process" value="btc" checked="checked">
                            <img src="{{ asset('assets/images/curbtc.png') }}" alt="" class="process-img">
                        </label>
                        <label for="process_43">
                            <input type="radio" name="type" id="process_43" class="process" value="ltc">
                            <img src="{{ asset('assets/images/curltc.png') }}" alt="" class="process-img">
                        </label>
                        <label for="process_48">
                            <input type="radio" name="type" id="process_48" class="process" value="eth">
                            <img src="{{ asset('assets/images/cureth.png') }}" alt="" class="process-img">
                        </label>
                        <label for="process_68">
                            <input type="radio" name="type" id="process_68" class="process" value="doge">
                            <img src="{{ asset('assets/images/curdoge.png') }}" alt="" class="process-img">
                        </label>
                        <label for="process_79">
                            <input type="radio" name="type" id="process_79" class="process" value="dash">
                            <img src="{{ asset('assets/images/curdash.png') }}" alt="" class="process-img">
                        </label>
                        <label for="process_69">
                            <input type="radio" name="type" id="process_69" class="process" value="usd">
                            <img src="{{ asset('assets/images/curusd.png') }}" alt="" class="process-img">
                        </label>
                    </div>
                </div>

            </div>
        </div>
        <!-- /.row -->
    </div><!-- /.container-fluid -->
{% endblock %}

{% block javascripts %}
    <form id="balance-form" method="post" action="{{ path('client_contract_payment_balance') }}"><input id="drop-balance" name="drop" type="hidden" value="" /></form>
    <form id="drop-form" method="post" action="{{ path('client_contract_payment') }}"><input id="drop" name="drop" type="hidden" value="" /></form>
    <script>
        $(document).ready(function () {
            $('#balance-contract').click(function () {
                $("#drop-balance").val('{{ plan.priority~plan.level~plan.id }}');
                $("#balance-form").submit();
            });
        });
    </script>
{% endblock %}

templates/backend/client/dashboard.html.twig
{% extends "base.html.twig" %}

{% block title %}Dashboard{% endblock %}

{% block content %}
    <div class="container-fluid">
        <!-- Small boxes (Stat box) -->
        <div class="row">

            <div id="menu" class="col-sm-3 acc-menu">
                {% include 'backend/client/left-menu.html.twig' %}
            </div>

            <div class="col-sm-9 acc-stat">
                <div class="col-lg-3 acc-stat-block">
                    <div class="acc-stat-top">
                        <p class="text-left">Contratos activos</p>
                        <span>{{ account.activeContracts }}</span>
                    </div>
                    <div class="acc-stat-bottom">
                        <a href="#" class="deposit">Mis Contratos</a>
                    </div>
                </div>
                <div class="col-lg-3 acc-stat-block">
                    <div class="acc-stat-top">
                        <p class="text-left">Capital activo</p>
                        <span>${{ account.activeCapital }}</span>
                    </div>
                    <div class="acc-stat-bottom">
                        <a href="{{ path('client_contract') }}" class="deposit">Contratar</a>
                    </div>
                </div>
                <div class="col-lg-3 acc-stat-block">
                    <div class="acc-stat-top">
                        <p class="text-left">Disponible</p>
                        <span>${{ account.balance }}</span>
                    </div>
                    <div class="acc-stat-bottom">
                        <a href="#" class="deposit">Retirar</a>
                    </div>
                </div>
                <div class="col-lg-3 acc-stat-block">
                    <div class="acc-stat-top">
                        <p class="text-left">Retenido</p>
                        <span>${{ account.retained }}</span>
                    </div>
                    <div class="acc-stat-bottom">
                        <a href="#" class="deposit">Ver histórico</a>
                    </div>
                </div>

                        {% if app.user.account.bestPlan is not null %}
                            <div class="col-xs-12 referral-link">
                                <div class="col-lg-3 referral-link-left">
                                    Link para referidos
                                </div>
                                <div class="col-lg-9 referral-link-right">
                                    <div class="col-lg-9">
                                        <span id="myTooltip"></span>
                                        <input type="text" class="text-center" id="myInput" readonly 
                                               value="{{ absolute_url(path('app_register_with_sponsor',{'sponsor_code':app.user.sponsorCode})) }}">
                                    </div>
                                    <div class="col-lg-3 text-center">
                                        <button onclick="myFunction()" class="link success">Copiar</button>
                                    </div>
                                </div>
                            </div>
                        {% endif %}

                        {% if lastTransactions|length>0 %}
                            <div class="col-xs-12">
                                <div class="last-operations-container col-xs-12 m-t-25">
                                    <h3 class="acc-p last-operations-title">&Uacute;ltimas transacciones</h3>
                                    <table class="table m-t-25">
                                        <thead>
                                            <tr>
                                                <th>Moneda</th>
                                                <th>Concepto</th>
                                                <th>Fecha</th>
                                                <th>Importe</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for t in lastTransactions %}
                                                <tr>
                                                    <td class="text-center"><img src="{{ asset('assets/images/curbtc.png') }}"></td>
                                                    <td>{{ t.concept }}</td>
                                                    <td>{{ t.date|date('d-m-Y h:i a') }}</td>
                                                    <td class="text-right">{{ t.credit>0?t.credit:t.debit }}</td>
                                                </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        {% endif %}

                <div class="col-xs-12">
                    <a id="test" href="#">Update account</a>
                </div>

            </div>
        </div>
        <!-- /.row -->
    </div><!-- /.container-fluid -->
{% endblock %}

{% block javascripts %}
    <script>
        function myFunction() {
            var copyText = document.getElementById("myInput");
            copyText.select();
            document.execCommand("copy");
        }
        window.onload = function () {
            document.querySelector('.link.success').addEventListener('click', () => console.log('Copy done.'));
        };

        $(document).ready(function () {
            $("#test").click(function () {
                $.ajax('{{ path('client_account_update') }}')
                        .done(function (e) {
                            console.log(e)
                        });
            });
        });
    </script>
{% endblock %}

templates/backend/client/left-menu.html.twig
<div class="col-md-6 text-center">
    <a href="{{ path('client_dashboard') }}" class="{{ subactive=='dashboard'?'active':'' }}">
        <i class="fa fa-home" aria-hidden="true"></i>
        Dashboard
    </a>
</div>
<div class="col-md-6 text-center">
    <a href="{{ path('client_contract') }}"  class="{{ subactive=='contract'?'active':'' }}">
        <i class="fa fa-database" aria-hidden="true"></i>
        Contratos
    </a>
</div>
<div class="col-md-6 text-center">
    <a href="#">
        <i class="fa fa-university" aria-hidden="true"></i>
        Mis Contratos
    </a>
</div>
<div class="col-md-6 text-center">
    <a href="#">
        <i class="fa fa-money" aria-hidden="true"></i>
        Retiros
    </a>
</div>
<div class="col-md-6 text-center">
    <a href="#">
        <i class="fa fa-group" aria-hidden="true"></i>
        Referidos
    </a>
</div>
<div class="col-md-6 text-center">
    <a href="#">
        <i class="fa fa-history" aria-hidden="true"></i>
        Historial
    </a>
</div>
<div class="col-md-6 text-center">
    <a href="#">
        <i class="fa fa-gear" aria-hidden="true"></i>
        Configuración
    </a>
</div>