src/Entity/Plan.php
<?php

namespace App\Entity;

use App\Repository\PlanRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use App\Classes\StringUtil;

/**
 * @ORM\Entity(repositoryClass=PlanRepository::class)
 */
class Plan {

    public const COLORS = [
        'background' => [
            1 => 'bg-plan-starter',
            2 => 'bg-plan-medium',
            3 => 'bg-plan-advanced',
            4 => 'bg-plan-expert'
        ],
        'border' => [
            1 => 'bg2-plan-starter',
            2 => 'bg2-plan-medium',
            3 => 'bg2-plan-advanced',
            4 => 'bg2-plan-expert'
        ]
    ];

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $name;

    /**
     * @ORM\Column(type="integer")
     */
    private $level;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $value;

    /**
     * @ORM\Column(type="integer")
     */
    private $priority;

    /**
     * @ORM\OneToMany(targetEntity=Account::class, mappedBy="bestPlan")
     */
    private $accounts;

    /**
     * @ORM\OneToMany(targetEntity=Contract::class, mappedBy="plan")
     */
    private $contracts;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $minPayment;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $maxPayment;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $avePayment;

    public function __construct()
    {
        $this->accounts = new ArrayCollection();
        $this->contracts = new ArrayCollection();
    }

    public function getCompleteName() {
        return $this->name . ' ' . StringUtil::numberToRoman($this->level);
    }

    public function compareTo(Plan $other = null): ?int {

        if (empty($other) || ($this->priority > $other->getPriority())) {
            return 1;
        } elseif ($this->priority < $other->getPriority()) {
            return -1;
        }
        return 0;
    }

    public function getId(): ?int {
        return $this->id;
    }

    public function getName(): ?string {
        return $this->name;
    }

    public function setName(string $name): self {
        $this->name = $name;

        return $this;
    }

    public function getLevel(): ?int {
        return $this->level;
    }

    public function setLevel(int $level): self {
        $this->level = $level;

        return $this;
    }

    public function getValue(): ?string {
        return $this->value;
    }

    public function setValue(string $value): self {
        $this->value = $value;

        return $this;
    }

    public function getPriority(): ?int {
        return $this->priority;
    }

    public function setPriority(int $priority): self {
        $this->priority = $priority;

        return $this;
    }

    /**
     * @return Collection|Account[]
     */
    public function getAccounts(): Collection
    {
        return $this->accounts;
    }

    public function addAccount(Account $account): self
    {
        if (!$this->accounts->contains($account)) {
            $this->accounts[] = $account;
            $account->setBestPlan($this);
        }

        return $this;
    }

    public function removeAccount(Account $account): self
    {
        if ($this->accounts->contains($account)) {
            $this->accounts->removeElement($account);
            // set the owning side to null (unless already changed)
            if ($account->getBestPlan() === $this) {
                $account->setBestPlan(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Contract[]
     */
    public function getContracts(): Collection
    {
        return $this->contracts;
    }

    public function addContract(Contract $contract): self
    {
        if (!$this->contracts->contains($contract)) {
            $this->contracts[] = $contract;
            $contract->setPlan($this);
        }

        return $this;
    }

    public function removeContract(Contract $contract): self
    {
        if ($this->contracts->contains($contract)) {
            $this->contracts->removeElement($contract);
            // set the owning side to null (unless already changed)
            if ($contract->getPlan() === $this) {
                $contract->setPlan(null);
            }
        }

        return $this;
    }

    public function getMinPayment(): ?string
    {
        return $this->minPayment;
    }

    public function setMinPayment(string $minPayment): self
    {
        $this->minPayment = $minPayment;

        return $this;
    }

    public function getMaxPayment(): ?string
    {
        return $this->maxPayment;
    }

    public function setMaxPayment(string $maxPayment): self
    {
        $this->maxPayment = $maxPayment;

        return $this;
    }

    public function getAvePayment(): ?string
    {
        return $this->avePayment;
    }

    public function setAvePayment(string $avePayment): self
    {
        $this->avePayment = $avePayment;

        return $this;
    }

}

templates/base.html.twig
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="{{ asset('assets/images/favicon.png') }}">
        <title>Solid Assets {% block title %}{% endblock %}</title>
        <!-- CSS -->
        <link href="{{ asset('assets/css/bootstrap.css') }}" rel="stylesheet" />
        <link href="{{ asset('assets/plugins/fontawesome/css/font-awesome.min.css') }}" rel="stylesheet" />
        <link href="{{ asset('assets/css/style.css') }}" rel="stylesheet" />
        <!--[if lt IE 9]>
          <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
          <link rel="stylesheet" href="{{ asset('assets/css/nav-ie.css') }}" />
        <![endif]-->
        <link href="{{ asset('assets/css/nav.css') }}" rel="stylesheet" />
        {% if backend is defined %}
            <link href="{{ asset('assets/css/backend.css') }}" rel="stylesheet" />
        {% endif %}
        <!-- Scripts -->
        <script src="{{ asset('assets/js/jquery.js') }}"></script>
        <script src="{{ asset('assets/js/bootstrap.js') }}"></script>
        <script src="{{ asset('assets/js/responsive-nav.js') }}"></script>
    </head>
    <body style="background: {{ backend is defined ? '#e8e8e8':'white'}};">

        <header class="clearfix {{ active=='security'?'hidden':'' }}">
            <a href="{{ path('homepage') }}" data-scroll>
                <img class="nav-logo logo" src="{{ asset('assets/images/sa-logo-w.png') }}" />
            </a>
            <nav class="nav-collapse">
                <ul>
                    {% if (is_granted('ROLE_CLIENT') or is_granted('ROLE_ADMIN')) and backend is not defined %}
                        <li class="{{ active=='members'?'active':'' }}"><a href="{{ path('client_dashboard') }}" data-scroll>Dashboard</a></li>
                        {% endif %}
                    <li class="{{ active=='homepage'?'active':'' }}"><a href="{{ path('homepage') }}" data-scroll>Inicio</a></li>
                    <li class="{{ active=='solid'?'active':'' }}"><a href="{{ path('solid') }}" data-scroll>Solid</a></li>
                    <li class="{{ active=='faq'?'active':'' }}"><a href="{{ path('faq') }}" data-scroll>F.A.Q.</a></li>
                    <li class="{{ active=='contact'?'active':'' }}"><a href="{{ path('contact') }}" data-scroll>Contacto</a></li>
                        {% if is_granted('ROLE_CLIENT') or is_granted('ROLE_ADMIN') %}
                        <li class="visible-xs"><a href="{{ path('app_logout') }}" data-scroll>Salir</a></li>
                        {% else %}
                        <li class="visible-xs"><a href="{{ path('app_login') }}" data-scroll>Entrar</a></li>
                        {% endif %}
                </ul>
            </nav>
            {% if is_granted('ROLE_CLIENT') or is_granted('ROLE_ADMIN') %}
                <a class="btn-lg btn-solid btn-login hidden-xs" href="{{ path('app_logout') }}">Salir</a>
            {% else %}
                <a class="btn-lg btn-solid btn-login hidden-xs" href="{{ path('app_login') }}">Entrar</a>
            {% endif %}
        </header>

            {% if is_granted('ROLE_CLIENT') or is_granted('ROLE_ADMIN') %}
                <div class="col-xs-12 user-data">
                    <span class="username">{{ app.user.firstname }}</span>
                    {% if is_granted('ROLE_CLIENT') and app.user.account.bestPlan is not null %}
                        <i class="fa fa-trophy" style="color:{{ app.user.account.color }}"
                           title="Nivel {{ app.user.account.bestPlan.completeName }}"></i>
                    {% endif %}
                    {% if app.user.mySponsor is not null %}
                        <span>Patrocinador: {{ app.user.mySponsor.firstname }}</span>
                    {% endif %}
                </div>
            {% endif %}

        <section>
            {% for flash_message in app.session.flashbag.get('success') %}
                <div class="flash-notice">
                    <i class="fa fa-times btn-close-flash"></i>
                    {{ flash_message }}
                </div>
                <script>
                    $(document).ready(function () {
                        $(".btn-close-flash").click(function () {
                            $(".flash-notice").hide();
                        });
                    });
                </script>
            {% endfor %}


            {% block content %}{% endblock %}

        </section>

            <footer class="col-xs-12">
                <div class="row">
                    <div class="paragraph text-center">
                        <ul class="footer-nav">
                            <li><a href="{{ path('homepage') }}">Inicio</a></li>
                            <li><a href="{{ path('solid') }}">Solid</a></li>
                            <li><a href="{{ path('faq') }}">F.A.Q.</a></li>
                            <li><a href="{{ path('contact') }}">Contacto</a></li>
                            <li><a href="{{ path('terms_of_use') }}">Términos de uso</a></li>
                            <li><a href="{{ path('cookies_policy') }}">Políticas de cookies</a></li>
                        </ul>
                    </div>
                    <div class="paragraph text-center">
                        <a href="{{ path('homepage') }}"><img class="logo-footer" src="{{ asset('assets/images/sa-logo-gold.png') }}" /></a>
                </div>
            </div>
        </footer>

                    <script src="{{ asset('assets/js/fastclick.js') }}"></script>
                    <script src="{{ asset('assets/js/scroll.js') }}"></script>
                    <script src="{{ asset('assets/js/fixed-responsive-nav.js') }}"></script>
                    {% block javascripts %}{% endblock %}

    </body>
</html>